services:
  memory-test:
    image: golang:1.25
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - MEMORY_LIMIT_MB=256 # capable limt
      - MEMORY_RETRY_AFTER=10
      # - MEMORY_LIMIT_MB=600 # fails
      - RATE_LIMIT_REQUESTS_PER_MINUTE=120 # observable
      # - RATE_LIMIT_REQUESTS_PER_MINUTE=600 # not easily observable
    command: go run main.go
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
